Packaging
netsec-ethz/bootstrapper pull request #5
Opened 2021-06-11 11:33 UTC by FR4NK-W

Add build rules and files to produce debian and rpm packages
Improve build instructions

2021-06-14 09:14 UTC, marcfrei approved these changes

2021-06-14 10:10 UTC, matzf commented on .bazel-build-env
> +sed -i "s/^ENV_PKG_VERSION = .*/ENV_PKG_VERSION = \"${PKG_VERSION_SCION_BOOTSTRAPPER}\"/" BUILD.bazel &>/dev/null
I understand this part is analogous from the setup in scion-builder; is there really no way to do this _without_ modifying the build files? Otherwise, wouldn't it maybe be a bit clearer if we move this to the Makefile (as part of the bazel target) -- it seems a bit too magic to me here in this file, I have no clue how/when this script is invoked.

2021-06-14 12:32 UTC, matzf commented on res/packaging/debian/DEBIAN/postinst
> +        iface=$(ip addr show | awk '/inet.*brd/{print $NF; exit}')
This extracts the last field of a matching IP address entry, where, in many cases, the device name is repeated. However, this field is called "label" which (apparently) is not necessarily identical with the device name. Also, the label is not necessarily the last field (sometimes the validity seems to be on the same line).
One option to improve this: `ip -oneline addr show` will put each address entry on a single line, so the device name in the first field can be parsed more easily. 

Also note that the regex matches both IPv4 and IPv6 (`inet`/`inet6`), not sure this is intentional. You can instead use the flags -4 and -6 to restrict to IP address types. 
I _guess_ that the `brd` match is to exclude the loopback interface. Maybe make this explicit (`grep -v lo`).

The comment mentions "active" network interfaces but it could actually be showing interfaces that are not up. Not sure whether that's what's meant, but `ip addr show` has a filter `up` to list only running interfaces.

Putting all together:
```
iface=$(ip -oneline -4 address show up | awk '$2!="lo"{print $2;exit}')
```


Aside: I just found out that `ip` has an undocumented `-json` option :bulb:

2021-06-14 12:32 UTC, matzf commented on res/packaging/debian/etc/scion/bootstrapper.toml
> +        # Whether to enable the fake discovery or not (default false)
Nit: mixed tabs/spaces

2021-06-14 12:34 UTC, matzf requested changes
Looks good, just a bunch of picky comments.

2021-06-14 13:20 UTC, FR4NK-W commented on Makefile
> +bazel: go_deps.bzl
Done

2021-06-14 13:20 UTC, FR4NK-W commented on Makefile
> +package_deb: package
Good point, done

2021-06-14 13:20 UTC, FR4NK-W commented on Makefile
> +	$(file > ./go_deps.bzl,$(go_deps_boilerplate))
Why should they be combined?
The `go_deps.bzl` target only needs to be run when the `go_deps.bzl` file does not exist or is corrupted. Updating a syntactically valid `go_deps.bzl` does not require overwritting with the boilerplate.

2021-06-14 13:20 UTC, FR4NK-W commented on README.md
> +To update the `go_deps.bzl` file and the dependencies Bazel uses from the `go.mod` module file, run `make gazelle`.
See above, I don't see the reason for that. Probably I'm missing something.

2021-06-14 13:20 UTC, FR4NK-W commented on WORKSPACE
> +        "https://github.com/bazelbuild/rules_pkg/releases/download/0.3.0/rules_pkg-0.3.0.tar.gz",
Updated, need to now explicitly set/search for the `rpmbuild` toolchain.

2021-06-14 13:20 UTC, FR4NK-W commented on WORKSPACE
> +        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.20.0/bazel-gazelle-v0.20.0.tar.gz",
Updated, v0.23.0 breaks, whereas v0.22.3 was stil fine, with the message:
>ERROR: ~/.cache/bazel/_bazel_user/hash/external/bazel_gazelle/repo/BUILD.bazel:3:11: no such target '@org_golang_x_tools//go/vcs:vcs': target 'vcs' not declared in package 'go/vcs' defined by ~/.cache/bazel/_bazel_user/hash/external/org_golang_x_tools/go/vcs/BUILD.bazel and referenced by '@bazel_gazelle//repo:repo'
Reordering the rules fixes it, because of overrides:
https://github.com/bazelbuild/bazel-gazelle/issues/561#issuecomment-506047843

2021-06-14 13:20 UTC, FR4NK-W commented on go.mod
>  replace github.com/insomniacslk/dhcp => github.com/stapelberg/dhcp v0.0.0-20190429172946-5244c0daddf0
Because it does not rely on u-root for the client library (u-root depending on calls that do not exist/are not implemented for non-Linux).
So basically for this commit:
https://github.com/stapelberg/dhcp/commit/5244c0daddf004bddd5d5b0c23f4cf645be0cea7

2021-06-14 13:20 UTC, FR4NK-W commented on res/packaging/debian/DEBIAN/postinst
> +        chmod +x /etc/dhcp/dhclient-enter-hooks.d/bootstrapper
Good point, much cleaner

2021-06-14 13:20 UTC, FR4NK-W commented on .bazel-build-env
> +sed -i "s/^ENV_PKG_VERSION = .*/ENV_PKG_VERSION = \"${PKG_VERSION_SCION_BOOTSTRAPPER}\"/" BUILD.bazel &>/dev/null
>  is there really no way to do this without modifying the build files?

Not that I am aware of, no. You can do stamping on the go_binary task, but not pkg_deb surprisingly, https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#stamping-with-the-workspace-status-script.
The script is invoked when bazel is run, it needs to be passed as `--workspace_status_command=` at least for the binary stamping to work.

2021-06-14 14:16 UTC, FR4NK-W commented on BUILD.bazel
> +	"scion-daemon",
Done

2021-06-14 14:16 UTC, FR4NK-W commented on res/packaging/debian/DEBIAN/postinst
> +        iface=$(ip addr show | awk '/inet.*brd/{print $NF; exit}')
Thanks for the pointer :slightly_smiling_face: 

>Also note that the regex matches both IPv4 and IPv6 (inet/inet6), not sure this is intentional.

I don't see why we should exclude IPv6. We do not support DHCP on IPv6, but the DNS based mechanisms still work.

> I guess that the brd match is to exclude the loopback interface. Maybe make this explicit (grep -v lo).

And to get an interface on which we can broadcast.

>ip addr show has a filter up to list only running interfaces.

Yes, good catch.

Went with something very similar to your suggestion.

2021-06-14 14:16 UTC, FR4NK-W commented on res/packaging/debian/etc/scion/bootstrapper.toml
> +        # Whether to enable the fake discovery or not (default false)
Done

2021-06-14 14:17 UTC, matzf commented on Makefile
> +	$(file > ./go_deps.bzl,$(go_deps_boilerplate))
The important point is that the target that should be called to update the file is `go_deps.bzl: go.mod` so that make can do it's normal thing and only run the target if the `go.mod` file is newer than the `go_deps.bzl`. If you want to keep the resetting in a separate, additional (phony) target, that's fine too.
If I recall correctly, in scionproto/scion we always wipe the file (i.e. reset it with the boilerplate pass thing) to ensure that dependencies that were removed from go.mod are also removed from this file. There is a `-prune` option to `update-repos`, but this was seemingly not effective.

2021-06-14 15:29 UTC, FR4NK-W commented on WORKSPACE
> +)
Done

2021-06-14 15:29 UTC, FR4NK-W commented on WORKSPACE
> +    go_version = "1.15.6",
Done

2021-06-14 15:29 UTC, FR4NK-W commented on WORKSPACE
> +        "https://github.com/bazelbuild/rules_go/releases/download/v0.22.4/rules_go-v0.22.4.tar.gz",
Done

2021-06-16 08:11 UTC, FR4NK-W commented on Makefile
> +	$(file > ./go_deps.bzl,$(go_deps_boilerplate))
Updated

2021-06-16 12:07 UTC, matzf commented on go.mod
>  replace github.com/insomniacslk/dhcp => github.com/stapelberg/dhcp v0.0.0-20190429172946-5244c0daddf0
Ok, all clear as long as it's intentional :)

2021-06-16 12:08 UTC, matzf commented on .bazel-build-env
> +sed -i "s/^ENV_PKG_VERSION = .*/ENV_PKG_VERSION = \"${PKG_VERSION_SCION_BOOTSTRAPPER}\"/" BUILD.bazel &>/dev/null
:sadpanda: Ok.

2021-06-16 12:10 UTC, matzf approved these changes
:+1:

2021-06-16 12:25 UTC, merged